include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - '**.config.dart'

linter:
  rules:
    always_use_package_imports: false
    prefer_relative_imports: true
    prefer_single_quotes: true
    sort_constructors_first: true
