name: todo_app
description: Yandex school TODO app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^1.5.3
  json_annotation: ^4.6.0
  logging: ^1.0.2
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  hive_generator: ^1.1.3
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.1

flutter:
  generate: true
  uses-material-design: true
