name: todo_app
description: Yandex school TODO app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  injectable: ^1.5.3
  logging: ^1.0.2

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.4
  lint: ^1.8.2

flutter:
  generate: true
  uses-material-design: true
