name: Flutter CI
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          chanel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
    timeout-minutes: 10
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          chanel: 'stable'
      - run: flutter pub get
      - run: flutter test
    timeout-minutes: 10
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          chanel: 'stable'
      - run: flutter build apk --split-per-abi --flavor prod
    timeout-minutes: 10

